### ISSUE TITLE
Move unit tests to tests directory on top

### ISSUE THREAD

**Issue by ManaSugi** [libseccomp-rs/libseccomp-rs#107]
Currently, all unit tests for the `libsecomp` crate is  under the same file as the to-be-tested code.
I think it's right to put unit tests with the production code as Rust book mentioned [here](https://doc.rust-lang.org/book/ch11-03-test-organization.html), but we'll lose an overview and a clear separation between production and test code. 
Also, the files'll grow huge while containing both.

Hence, I'd like to move unit tests to a `tests` directory on top for making the code clean.
Originally, the `tests` directory is for integration tests, but it's good for the future work.

```
├── libseccomp-rs
│   └── libseccomp
│   └── libseccomp-sys
│   └── tests
│        └── xxx.rs
```

Or, we'll need to split the current huge `lib.rs` as module like `notify.rs`

**Comment by rusty-snake** [comment]
IIRC a `tests/foo.rs` file is an external crate which can only test the public API and has no access (read/write/create/mock/...) to private types/function/fields. Moving the current `mod tests` in a `tests.rs` would be better then.

**Comment by boustrophedon** [comment]
I tried doing this a week or two ago because I didn't realize the tests were meant to run with --test-threads=1 (due to one or more of the tests modifying global state and causing failures sometimes - I think it was specifically the reset one) and it wasn't too much work, there were only a couple functions that weren't exposed.

Additionally, each file in the top level tests/ directory gets run as a separate process, so you can split out the tests that modify global state and not have to run the tests single-threaded.
