### ISSUE TITLE
EBUSY not in SeccompErrno

### ISSUE THREAD

**Issue by rusty-snake** [libseccomp-rs/libseccomp-rs#161]
SeccompErrno contains all errnos returned by the libseccomp api. However if you set `ApiSysRawRc` the errno from the kernel seccomp api is returned instead. This raises to problems
1. The descriptions of the errno are not (always) correct.
2. The kernel seccomp api can return errnos which are not returned by the libseccomp api.

<span></span>1. Can be ignored IMHO because if you set `ApiSysRawRc` you are interested in the errno and perform your own handling of it instead of logging it (and die). Also it's limited what we can do. However 2. is problematic if you want to match on an errno which is not covered by SeccompErrno.
Looking at the manpage of `seccomp(2)` list only `EBUSY` as not covered errno.

**Comment by to-json** [comment]
https://github.com/libseccomp-rs/libseccomp-rs/pull/205 should cover this, unless I missed something

**Comment by to-json** [comment]
(I did audit the descriptions a bit; the ones in libseccomp RS mostly cover the related case in the man page, but with broader language, a format I continued for this, but I would be happy to use the much more exacting phrasing from the man page ('EBUSY  While installing a new filter, the SECCOMP_FILTER_FLAG_NEW_LISTENER flag was specified, but a previous filter  had  already  been installed with that flag.')

actually, I'ma go update that to be somewhat more specific rn

**Comment by rusty-snake** [comment]
> in the man page

Which man page?

> but with broader language

It's a bit difficult because there are errnos from the kernel (only returned when sys_raw_rc is used) and errnos from libseccomp (usually returned). The meaning of an errno can differe between these two. And it can differ between functions in libseccomp (e.g. "EEXIST  In the case of seccomp_arch_add() the architecture  already  exists  and  in the case of seccomp_arch_remove() the architecture does not exist.").

**Comment by to-json** [comment]
> Which man page?
`seccomp(2)`, I should have specified

> The meaning of an errno can differ between these two.

Oh, I fully missed this layer of nuance, that makes a lot of sense, and makes it clearer why EBUSY, returned primarily by libseccomp, could be more specific than many of the others. I put in a tighter message, but if I'm understanding you correctly, it would be most readable to just reproduce the libseccomp error message directly? I'll push that up in a cpl hours if so, gotta step away for a bit.

**Comment by ManaSugi** [comment]
@to-json Thanks for handling this issue😄!

@rusty-snake 
Regarding `seccomp(2)`, we can handle all errno by adding `EBUSY`, but errno of `seccomp_export_{bpf,pfc}` cannot be covered because these two functions will also return arbitray system's errno directly if  `ApiSysRawRc` is set.
Ref. https://github.com/seccomp/libseccomp/commit/34bf78abc9567b66c72dbe67e7f243072162a25f#diff-180c1c48614a941a92369affdf11a798b80ca8db3ad6d2d7c79338fd3d7a64d4L639-R695

For example, if the file descriptor of `seccomp_export_{bpf,pfc}` is invalid with `ApiSysRawRc` is set, they returns `-EBADFD` that is not supported in our libseccomp-rs.
https://github.com/seccomp/libseccomp/commit/34bf78abc9567b66c72dbe67e7f243072162a25f#diff-0ddcb17d999779c2215ffc4ec65c3802daa3ea49f9576efc596eaed738af9b7fR55-R56

To deal with the existing functions (and also the future ones), we might want to consider our `SeccompErrno` design because it's hard to for us to tackle all system's errno being returned. But, for the time being, it's good to add `EBUSY` for `seccomp(2)`.
What do you think?

**Comment by ManaSugi** [comment]
@rusty-snake Thanks for the comment.

And also, we can simply add [all errno supported by libc crate](https://docs.rs/libc/latest/src/libc/unix/linux_like/linux/mod.rs.html#3683) to `SecccompErrno`  like #205. 
This doesn't generate any incompatible change and users don't need to recognize the raw mode.
The error messages at [strerror](https://github.com/libseccomp-rs/libseccomp-rs/blob/main/libseccomp/src/error.rs#L46) can be like `"Returned the system's errno because of ApiSysRawRc enabled"`.
