### ISSUE TITLE
Builder like interface for ScmpFilterContext

### ISSUE THREAD

**Issue by rusty-snake** [libseccomp-rs/libseccomp-rs#180]
### Discussed in https://github.com/libseccomp-rs/libseccomp-rs/discussions/154

<div type='discussions-op-text'>

<sup>Originally posted by **rusty-snake** May  7, 2022</sup>
What do you think about extending `ScmpFilterContext` with an Builder like interface?

```rust
ScmpFilterContext::new_filter(ScmpAction::Allow)?
    .add_arch(ScmpArch::X8664)?;
    .add_rule(
        ScmpAction::Errno(libc::EPERM),
        ScmpSyscall::from_name("chroot")?,
    )?
    .add_rule(...)?
    .add_rule(...)?
    .add_rule_conditional(...)?
    .set_ctl_log(true)?
    .load()?;
```

</div>

**Comment by ManaSugi** [comment]
@rusty-snake 

Thank you for the proposal.
But I think the builder pattern could not be suitable for libseccomp API because most users of libseccomp-rs use it for container runtimes such as  [kata-containers](https://github.com/kata-containers), [youki](https://github.com/containers/youki) and etc. and they apply the seccomp filter based on a static configuration file, [runtime-spec](https://github.com/opencontainers/runtime-spec/blob/main/config-linux.md#seccomp). In that case, they want to use our APIs on demand for each configuration. If they want to achieve this with the builder pattern, it would be difficult to use it.

What do you think?

**Comment by rusty-snake** [comment]
[Command](https://doc.rust-lang.org/std/process/struct.Command.html) has a builder like interface but can also be used like `ScmpFilterContext` works today (and sometimes you have to use it like this). This is because all the modification functions take and return references. So unless you relay on a `()` (in a `Result`) as return type, this would not affect existing users.

**Comment by rusty-snake** [comment]
I implemented this for `add_rule*`. It passes all tests w/o changes (as expected). However `add|remove_arch` are difficult because the return `Result<bool>` instead of `Result<()>`.

Instead of makeing a breaking change to them (for `add_rule*` it is a minor breaking change) I thought of a `ScmpFilterContext::with_arches(IntoIter<ScmpArch>)` and maybe someway to say `no_default/native_arch`. WDYT?

**Comment by ManaSugi** [comment]
@rusty-snake Thanks for the update.

We can also revert the change about `{add,remove}_arch}` in 16089338c7e579fbd80ce205a483be228a9bd03a instead of adding `with_arches`. In terms of simplicity, it is reasonable to be able to use `{add,remote}_arch}` in the builder pattern as well. Apart from the a breaking change, even if there is a user who wants to extract the `EEXIST` error,  they can call `is_arch_present()` in advance. I don't think the previous silent error brings about a serious problem.

**Comment by rusty-snake** [comment]
Thanks for remembering on the error rework.

I agree that the most users will use it as a ensure arch is/is not in the filter (idempotent) and the EEXIST case isn't very common.

> But, in the case of calling add,remove}_arch many times in the builder pattern, ScmpFilterContext::with_arches(IntoIter<ScmpArch>) is useful. Hmm...

We can do both :wink:

The amount of `add_rule*` is a builder will exceed the amount of arches in the most filters.

**Comment by ManaSugi** [comment]
Okay, let's revert the previous change `{add,remove}_arch` at first in order to apply the builder pattern.

> The amount of add_rule* in a builder will exceed the amount of arches in the most filters.
Yes...,
