### ISSUE TITLE
Update ScmpAction::Errno again

### ISSUE THREAD

**Issue by rusty-snake** [libseccomp-rs/libseccomp-rs#38]
#13 has changed `ScmpAction::Errno(u32)` to `ScmpAction::Errno(i32)` to make `ScmpAction::Errno(libc::EPERM)` as easy as possible.

However since you can only use `u16`, it would be good if it would be `ScmpAction::Errno(u16)`.
 Now my idea is to change it to `ScmpAction::Errno(u16)` and provide `ScmpAction::errno(errno: i32) -> Self` (this will also simplify `from_str`'s `val`).

**Comment by ManaSugi** [comment]
Thank you for raising this issue.
Is `ScmpAction::errno(errno: i32) -> Self` function mainly for a user who wants to use the  errno (`i32`) provided by `libc`?
I think most of Rust users use `libc` errno that is defined `i32`, so the existing `ScmpAction::Errno(i32)` is kindly for the users.
Of course,  I can understand the current implementation is a bit weird  because `SCMP_ACT_ERRNO` actually takes `u16` errno.
Hmm.. I'm not sure which one is the best. Actually, libseccomp-golang uses `i16` that is different from the original argument type (`u16`).
https://github.com/seccomp/libseccomp-golang/blob/main/seccomp.go#L413

**Comment by rusty-snake** [comment]
> Is ScmpAction::errno(errno: i32) -> Self function mainly for a user who wants to use the errno (i32) provided by libc?

Yeah, that is the idea.
1. Use the "correct" type as value and
2. be easy to use with `libc`

> Hmm.. I'm not sure which one is the best.

+1

**Comment by ManaSugi** [comment]
> 1. Use the "correct" type as value and
> 2. be easy to use with libc

It's good :), but If we start to support `ScmpAction::errno(i32), I guess nobody uses `ScmpAction::Errno(u16)` :(

**Comment by ManaSugi** [comment]
On second thought, most of Rustaceans will definitely use `libc::errno` when they want to specify `errno`, so I agree with using `ScmpAction::Errno(i32)` (as it is).  What do you think?

**Comment by rusty-snake** [comment]
I think it's ok to keep it as is, closing.
